convcd, cddb-functions, generic-functions: New cddb-functions file, adapt convcd for it's usage. Colours support in info/warn/error/die.

diff --git a/frontends/convcd b/frontends/convcd
--- a/frontends/convcd
+++ b/frontends/convcd
@@ -23,10 +23,11 @@ else
 	exit 1
 fi
 
-if [ -f $INCDIR/generic-functions.shlib -a -f $INCDIR/container-functions.shlib -a -f $INCDIR/audio-functions.shlib ]; then
+if [ -f $INCDIR/generic-functions.shlib -a -f $INCDIR/container-functions.shlib -a -f $INCDIR/audio-functions.shlib -a -f $INCDIR/cddb-functions.shlib ]; then
 	source $INCDIR/generic-functions.shlib
 	source $INCDIR/container-functions.shlib
 	source $INCDIR/audio-functions.shlib
+	source $INCDIR/cddb-functions.shlib
 else
 	echo "Can't load functions, exiting."
 	exit 1
@@ -34,10 +35,10 @@ fi
 
 set_masks() {
 	# Export title/artist/album/tracknum, then change FILE_MASK accordingly.
-	export TITLE="$(grep "${N}:" ${TMPDIR}/tracks.txt | cut -d: -f2 | sed -e 's^&^And^g' -e 's^\/^ - ^g' -e 's^\?^^g')"
-	export ARTIST="$(grep "${N}:" ${TMPDIR}/tracks-artists.txt | cut -d: -f2 | sed -e 's^&^And^g' -e 's^\/^ - ^g')"
-	export ALBUM="$(cat ${TMPDIR}/album.txt | grep "album:" | cut -d: -f2 | sed -e 's^&^And^g' -e 's^\/^ - ^g')"
-	export YEAR="$(cat ${TMPDIR}/album.txt | grep "year:" | cut -d: -f2)"
+	export TITLE="$(grep "${N}:" $TMPDIR/parsed_results | cut -d: -f3 | sed -e 's^&^And^g' -e 's^\/^ - ^g' -e 's^\?^^g')"
+	export ARTIST="$(grep "${N}:" ${TMPDIR}/parsed_results | cut -d: -f2 | sed -e 's^&^And^g' -e 's^\/^ - ^g')"
+	export ALBUM="$(grep "album:" ${TMPDIR}/parsed_results | cut -d: -f2 | sed -e 's^&^And^g' -e 's^\/^ - ^g')"
+	export YEAR="$(grep "year:" ${TMPDIR}/parsed_results | cut -d: -f2)"
 	export TRACKNUM="$I"
 	export ORIG_FMASK="$FILE_MASK"
 	export ORIG_DMASK="$DIR_MASK"
@@ -98,7 +99,7 @@ while getopts 'f:a:q:r:d:n:swbhmi' z; do
 		fi
 	;;
 	b)
-		set -e -x
+		set -x
 	;;
 	i)
 		export INTERACTIVE="1"
@@ -128,34 +129,49 @@ if [ -z $ACODEC ]; then
 fi
 
 export PARANOIA_OPTS="--never-skip=40 -d $CD_DEVICE"
-export CDDISCID_OPTS="$CD_DEVICE"
 
-cd-discid $CDDISCID_OPTS &> /dev/null
+cd-discid $CD_DEVICE &> /dev/null
 
 if [ "$?" = "1" ]; then
 	die "There is no CD in the drive to rip."
 fi
 
-info "Retrieving information about this CD from CDDB"
-cddb_query_info
-if [ -n "$CDDB_CACHE_HIT" ]; then
-	info "Retrieved information from cache, done."
-else
-	info "Retrieved information from CDDB, done."
+info "Querying disc for disc information"
+query_disc $CD_DEVICE
+
+info "Querying local cache about this CD"
+cddb_cache query $TMPDIR/parsed_results
+
+# Cache hit failed, query CDDB.
+if [ "$?" -gt 0 ]; then
+	# Ask CDDB about the current disc, cddb_query returns 0 if successful and 1 if it fails.
+	# If it fails use cddb_unknown to produce an Unknown Album template for the user to modify.
+	info "Cache query unsuccessful"
+	info "Retrieving information about this CD from CDDB"
+	cddb_query freedb.freedb.org/cgi-bin/cddb.cgi nobody+localhost+convcd+1.0 $TMPDIR/query_results
+	if [ "$?" -lt 1 ]; then
+		cddb_read freedb.freedb.org/cgi-bin/cddb.cgi nobody+localhost+convcd+1.0 $TMPDIR/query_results $TMPDIR/read_results
+		cddb_parse $TRACKS $TMPDIR/read_results $TMPDIR/parsed_results
+	else
+		cddb_unknown $TRACKS $TMPDIR/parsed_results
+	fi
 fi
-export ALBUM="`cat "${TMPDIR}"/album.txt | grep "album:" | cut -d: -f2 | sed 's^&^And^g'`"
-export YEAR="`cat "${TMPDIR}"/album.txt | grep "year:" | cut -d: -f2`"
-echo "Album: $ALBUM" >> "${TMPDIR}"/album-info.txt
-echo "Year of release: $YEAR" >> "${TMPDIR}"/album-info.txt
+
+export ALBUM="$(grep 'album:' "${TMPDIR}"/parsed_results | cut -d: -f2 | sed 's^&^And^g')"
+export YEAR="$(grep 'year:' "${TMPDIR}"/parsed_results | cut -d: -f2)"
+
+echo
+echo "Album title: ${ALBUM}" >> "${TMPDIR}"/album-info.txt
+echo "Year of release: ${YEAR}" >> "${TMPDIR}"/album-info.txt
 unset ALBUM
-for i in $(seq 0 $TRACKS); do
+for i in $(seq 0 "$TRACKS"); do
 	if [ ! "$(echo -n "$i" | wc -m)" = "2" ]; then
 		export N="0${i}"
 	else
 		export N="$i"
 	fi
 	set_masks
-	echo "Track $N: $TITLE by $ARTIST" >> $TMPDIR/album-info.txt
+	echo "Track $N: $TITLE by $ARTIST" >> "${TMPDIR}"/album-info.txt
 	restore_masks
 done
 cat "${TMPDIR}"/album-info.txt
@@ -163,16 +179,19 @@ cat "${TMPDIR}"/album-info.txt
 if [ -n "$INTERACTIVE" ]; then
 	echo -n "Do you want to edit the song titles, artist(s) and album name information now? (y/n) "; read answer
 	if [ "$answer" = "y" ]; then
-		$EDITOR "${TMPDIR}"/tracks.txt
-		$EDITOR "${TMPDIR}"/tracks-artists.txt
-		$EDITOR "${TMPDIR}"/album.txt
-		# Recalculate number of tracks to rip by using tracks.txt.
-		export TRACKS="$(cat "${TMPDIR}"/tracks.txt | wc -l)"
-		export TRACKS="$(expr $TRACKS - 1)"
+		$EDITOR $TMPDIR/parsed_results
+		# Recalculate number of tracks to rip by using parsed_results
+		# We count from zero, minus 2 for album/year in parsed_results.
+		export TRACKS="$(cat "${TMPDIR}"/parsed_results | wc -l)"
+		export TRACKS=$((${TRACKS}-3))
 	fi
 fi
 
+# Cache our result in our local cache.
+cddb_cache add "${TMPDIR}"/parsed_results
+
 for i in $(seq 0 $TRACKS); do
+	# Insanely complicated bit of code to do an insanely simple task, make all track numbers double-digit or higher.
 	if [ ! "$(echo -n "$i" | wc -m)" = "2" -a "$i" != "9" ]; then
 		export I="$i"
 		((I++))
